<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AMBAL" failures="1" tests="3" name="com.sevenrmartsupermarket.tests.LoginTest" time="8.904" errors="0" timestamp="2023-05-17T14:53:45 IST" skipped="0">
  <testcase classname="com.sevenrmartsupermarket.tests.LoginTest" name="verifyUserLogin" time="3.688">
    <failure message="expected [admin] but found [Admin]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [admin] but found [Admin]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.LoginTest.verifyUserLogin(LoginTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyUserLogin -->
  <system-out/>
  <testcase classname="com.sevenrmartsupermarket.tests.LoginTest" name="verifyErrorMessageOnInvalidUserLogin" time="2.949"/>
  <system-out/>
  <testcase classname="com.sevenrmartsupermarket.tests.LoginTest" name="verifySignInButtonText" time="2.267"/>
  <system-out/>
</testsuite> <!-- com.sevenrmartsupermarket.tests.LoginTest -->
